### ISSUE TITLE
divide by zero when affine applied to spectrum of all zeros.

### ISSUE THREAD

**Issue by pjgrandinetti** [deepanshs/mrsimulator#230]
I noticed that you get a divide by zero error if you apply an affine transform on a spectrum of all zeros. That is, if you have the wrong spectral width so that the spectrum is outside the window, then the affine gives an error.

**Comment by deepanshs** [comment]
Can you provide a minimal reproducible example?

**Comment by pjgrandinetti** [comment]
[STMAS_test.ipynb.zip](https://github.com/deepanshs/mrsimulator/files/9440290/STMAS_test.ipynb.zip)

**Comment by pjgrandinetti** [comment]
[STMAS_test.ipynb.zip](https://github.com/deepanshs/mrsimulator/files/9440298/STMAS_test.ipynb.zip)

**Comment by pjgrandinetti** [comment]
Error goes away with larger spectral_width=6e3

method = ST1_VAS(
    channels=["59Co"],
    magnetic_flux_density=7,  # in T
    rotor_angle=54.7359 * 3.14159 / 180,  # in rad (magic angle)
    spectral_dimensions=[
        SpectralDimension(
            count=256,
            spectral_width=6e3,  # in Hz
            reference_offset=-2.4e3,  # in Hz
            label="Isotropic dimension",
        ),
        SpectralDimension(
            count=512,
            spectral_width=10e3,  # in Hz
            reference_offset=-4e3,  # in Hz
            label="MAS dimension",
        ),
    ],
)

**Comment by deepanshs** [comment]
The error isn't coming from the affine transformation. The simulation runs just fine. The error you see is coming from the plot function following the simulation.

```py
cb1 = ax.imshow(dataset.real / dataset.real.max(), aspect="auto", cmap="gist_ncar_r")
```

Since, the spectrum is all zeros, `dataset.real / dataset.real.max()` is a 0/0 division error.
