### ISSUE TITLE
CSDM origin offset and reference issue

### ISSUE THREAD

**Issue by deepanshs** [deepanshs/mrsimulator#269]
## Equations

The CSDM `LinearDimension` defines coordinates as
`coordinates` = $\Delta x(J_k - Z_k) + b_k$,
where $J_k = [0, 1, ... N_k -1]$. When complex_fft=False,  $Z_k$ = 0. When complex fft=True, $Z_k = N_k/2$ for even $N_k$ else $(N_k-1)/2$

- `coordinates_offset` = $b_k$
- `increment` = $\Delta x_k$
- `count` = N

For NMR datasets, here are two cases---when origin_offset is defined at the receiver frequency, and origin_offset is defined at the reference frequency.

| | origin_offset $= w_\text{RF}$ | origin_offset $= w_\text{ref}$  |
|---|---|---|
|`complex_fft` = True | $w_\text{ref} = w_\text{RF} - b$ | $w_\text{RF} = w_\text{ref} + b$ |
|`complex_fft` = False, $N$ is odd | $w_\text{ref} = w_\text{RF} - (b + \frac{N-1}{2} \Delta x)$ | $w_\text{RF} = w_\text{ref} + (b + \frac{N-1}{2} \Delta x)$ |
|`complex_fft` = False, $N$ is even, $\Delta x$ > 0 | $w_\text{ref} = w_\text{RF} - (b + \frac{N}{2} \Delta x)$ | $w_\text{RF} = w_\text{ref} + (b + \frac{N}{2} \Delta x)$ |
|`complex_fft` = False, $N$ is even, $\Delta x$ < 0 | $w_\text{ref} = w_\text{RF} - (b + (\frac{N}{2} - 1) \Delta x)$ | $w_\text{RF} = w_\text{ref} + (b + (\frac{N}{2} - 1) \Delta x)$ |

The conversion from Hz -> ppm is `coordinates` / ${w_\text{ref}}$. The difference is that when origin_offset is ${w_\text{RF}}$, the value of ${w_\text{ref}}$ depends on how the LinearDimension is defined.

---

What happens to the origin offset for a data subset? 

- If the origin offset is $w_\text{ref}$, we retain both frequency and ppm dimension scale for the subset data but lose the information on $w_\text{RF}$. However, does $w_\text{RF}$ has meaning for a data subset?

- If the origin offset is $w_\text{RF}$, we lose the information on $w_\text{ref}$. Therefore, the subset data can only be represented in frequency dimension, not dimensionless ppm scale. We retain $w_\text{RF}$, which again seems meaning less for a data subset.

---

## Cases

1 **When dataset is the full spectrum**

| property | origin_offset $= w_\text{ref}$ | origin_offset $= w_\text{RF}$  |
|---|---|---|
| always known |  $w_\text{ref}$ | $w_\text{RF}$ |
| can be derived | $w_\text{RF}$ | $w_\text{ref}$ |
| information loss | - | - |
| `absolute_coordinates` | ✅ | ❌ |
| `coordinates` | ✅ | ✅ |
| `ppm_scale` (using above equations) | ✅ | ✅ |

2 **Subset of the full spectrum (keeping the `origin_offset` the same as the original dataset)**

| property | origin_offset $= w_\text{ref}$ | origin_offset $= w_\text{RF}$  |
|---|---|---|
| always known |  $w_\text{ref}$ | $w_\text{RF}$ |
| can be derived | -  | -  |
| information loss | $w_\text{RF}$ | $w_\text{ref}$ |
| `absolute_coordinates` | ✅ | ❌ |
| `coordinates` | ✅ | ✅ |
| `ppm_scale` (using above equations) | ✅ | ❌ |

3 **Subset of the full spectrum (updating the `origin_offset` to maintain the same ppm scale)**

| property | origin_offset $= w_\text{ref}$ | origin_offset $= w'_\text{RF}$  |
|---|---|---|
| always known |  $w_\text{ref}$ | $w'_\text{RF}$ |
| can be derived | -  | -  |
| information loss | $w_\text{RF}$ | $w_\text{RF}$ |
| `absolute_coordinates` | ✅ | ❌ |
| `coordinates` | ✅ | ✅ |
| `ppm_scale` (using above equations) | ✅ | ✅ |

## Scenarios 
- **When `origin_offset` is $w_\text{RF}$**. Case 1 and Case 2(subset has the same `origin_offset` as the original)
![original-1](https://github.com/deepanshs/mrsimulator/assets/21365911/95c6e6e7-5bdc-4429-a142-c575aa1ae201)
![subset-1](https://github.com/deepanshs/mrsimulator/assets/21365911/d2b8c09f-a4d5-4253-9134-27f4bdc69486)

**Test file** [scenario-1.zip](https://github.com/deepanshs/mrsimulator/files/11787884/scenario-1.zip)
**Summary** `origin_offset` is always $w_\text{RF}$. The coordinates in Hz are known. Since there is no evidence if the csdm object is a complete or a subset, $w_\text{ref}$ and therefore the coordinates in ppm are presumed incorrect.

- **When `origin_offset` is $w_\text{ref}$**. Case 1 and Case 2(subset has the same `origin_offset` as the original)
![original-2](https://github.com/deepanshs/mrsimulator/assets/21365911/ca7ae623-4b06-45aa-ac71-bb860960d466)
![subset-2](https://github.com/deepanshs/mrsimulator/assets/21365911/34b7de02-d23c-4bde-a627-0d48ce205764)

**Test file** [scenario-2.zip](https://github.com/deepanshs/mrsimulator/files/11787888/scenario-2.zip)
**Summary** `origin_offset` is always $w_\text{ref}$. The coordinates in Hz and ppm are always known. Since there is no evidence if the csdm object is a complete or a subset, the $w_\text{RF}$ is presumed incorrect.

**Comment by pjgrandinetti** [comment]
The assumption that the carrier frequency is at the center of the spectrum is the only way to encode both wRF and wref into o and b.
