### ISSUE TITLE
Bug in Minimizer(sf.LMFIT_min_function, fit_parameters, fcn_args=(sim, processor, sigma))

### ISSUE THREAD

**Issue by MHFrey** [deepanshs/mrsimulator#271]
Did you find a bug? Please help us improve by fill out the sections below. 👍
When I try to fit a simulation against a simulation the Minimizer crashes
**Describe the bug**

AttributeError: 'numpy.ndarray' object has no attribute '_set_unit'

**To Reproduce**

Create a jupyter notebook
load the "Least-Squares Fitting Example" from https://mrsimulator.readthedocs.io/en/stable/introduction/fitting_example.html
I did this by cutting and pasting each cell.

**Expected behavior**

Fit results as on the web page

**Desktop (please complete the following information):**

- OS: [Windows 10
- Python version: [e.g. 3.7.1] 3.10.9 in Anaconda environment Anaconda3-2023.03-1-Windows-x86_64
- `mrsimulator` version: [e.g. 0.3] 0.70, lmfit 1.2.1

**Additional context**

**Comment by mgiammar** [comment]
Thanks for the bug report. Can you also provide the versions of `csdmpy` and `astropy` Python libraries?

Can be obtained by running
`pip show csdmpy astropy`

**Comment by MHFrey** [comment]
csdumpy 0.5
astropy 5.1

These are in the standard release of Anaconda3 2023.03.1-1

**Comment by mgiammar** [comment]
It looks like astropy 5.1 is the issue. Try upgrading to astropy 5.3.

`pip install -u astropy 5.3`

**Comment by MHFrey** [comment]
All fixed.  Thank you for you amazingly quick help and solution.
