### ISSUE TITLE
crash when applying an apodization with a zero width

### ISSUE THREAD

**Issue by pjgrandinetti** [deepanshs/mrsimulator#284]
I get a crash when applying an apodization with a zero width:

processor = sp.SignalProcessor(
    operations=[
        sp.IFFT(),
        sp.apodization.Gaussian(FWHM="0 Hz"),
        sp.FFT(),
    ]
)

TypeError                                 Traceback (most recent call last)
Cell In[176], line 26
     17 processor = sp.SignalProcessor(
     18     operations=[
     19         sp.IFFT(),
   (...)
     22     ]
     23 )
     25 # Apply the processor to the simulation dataset
---> 26 processed_simulation = processor.apply_operations(dataset=sim.methods[0].simulation)
     28 plt.figure(figsize=(4.25, 3.0))
     29 ax = plt.subplot(projection="csdm")

File [~/Github/Software/mrsimulator/src/mrsimulator/signal_processor/__init__.py:80](https://file+.vscode-resource.vscode-cdn.net/Users/philip/Documents/Grandinetti%20Research/All%20Talks/2023/2023-07-Corning/py-scripts/~/Github/Software/mrsimulator/src/mrsimulator/signal_processor/__init__.py:80), in SignalProcessor.apply_operations(self, dataset, **kwargs)
     78     raise ValueError("The dataset must be a CSDM object.")
     79 for filters in self.operations:
---> 80     dataset = filters.operate(dataset)
     81 self.processed_dataset = dataset
     83 return dataset

File [~/Github/Software/mrsimulator/src/mrsimulator/signal_processor/apodization.py:43](https://file+.vscode-resource.vscode-cdn.net/Users/philip/Documents/Grandinetti%20Research/All%20Talks/2023/2023-07-Corning/py-scripts/~/Github/Software/mrsimulator/src/mrsimulator/signal_processor/apodization.py:43), in Apodization.operate(self, dataset)
     41 for i in dim_index:
     42     x = self.get_coordinates(dims[i])  # dims[i].coordinates
---> 43     apodization_vector = _get_broadcast_shape(self.fn(x), i, ndim)
     45     dv_indexes = self._get_dv_indexes(self.dv_index, n=len(dataset.y))
     47     for index in dv_indexes:

File [~/Github/Software/mrsimulator/src/mrsimulator/signal_processor/utils.py:18](https://file+.vscode-resource.vscode-cdn.net/Users/philip/Documents/Grandinetti%20Research/All%20Talks/2023/2023-07-Corning/py-scripts/~/Github/Software/mrsimulator/src/mrsimulator/signal_processor/utils.py:18), in _get_broadcast_shape(array, dim, ndim)
     16 for dim_ in dim:
     17     none[-dim_ - 1] = slice(None, None, None)
---> 18 return array[tuple(none)]

TypeError: 'float' object is not subscriptable

**Comment by deepanshs** [comment]
fixed in #286
